language: ruby
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.1

script: bundle exec rake spec

env:
  CODECLIMATE_REPO_TOKEN: 47bc411a11ccfed015bf25395d8204600c899e530c1c4beed1b7197aa61c6fb6

gemfile:
  - gemfiles/3.2.gemfile
  - gemfiles/4.0.gemfile
  - gemfiles/4.1.gemfile