language: ruby
rvm:
  - 2.0.0
  - 2.1.1
  - ruby-head

script:
  - bundle exec rake -f spec/dummy/Rakefile db:migrate
  - bundle exec rake spec cucumber

before_script:
  - cp spec/dummy/config/database.yml.travis spec/dummy/config/database.yml
  - mysql -e 'create database mg_test'
  - psql -c 'create database mg_test' -U postgres

env:
  - DB=sqlite
  - DB=mysql
  - DB=postgresql

gemfile:
  - gemfiles/rails_32.gemfile
  - gemfiles/rails_40.gemfile
  - gemfiles/rails_41.gemfile

addons:
  code_climate:
    repo_token: 47bc411a11ccfed015bf25395d8204600c899e530c1c4beed1b7197aa61c6fb6
  postgresql: "9.3"

matrix:
  allow_failures:
    - rvm: ruby-head
