# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e09b8a9e1a61ddfdf3b21d00051af8071303f30bd2250cfafd694e4d6415e9951a23c09ed2b27f503672f1eaebf8ab8805648d5c4d9960576ec4ca32a2fe9f3e

test:
  secret_key_base: 1f428e09c3d4886dd6350e2a850485663df56f501d0533d5bf0118ca285816433be3fd7a38ca68ff8e1e0b3adb99afa81320213e3787c35db94bd3d38c4aa73d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
